

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"    # MinIO API
      - "9001:9001"    # MinIO Console
    environment:
      # Root credentials (admin access)
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

      # Console address
      MINIO_CONSOLE_ADDRESS: ":9001"

      # Optional: Set server URL
      MINIO_SERVER_URL: "http://127.0.0.1:9000"

    volumes:
      - minio_data:/data
    restart: always
    entrypoint: >
      /bin/sh -c "
        minio server /data --console-address :9001 & 
        pid=$!;
        sleep 5;
        mc alias set local http://127.0.0.1:9000 minioadmin minioadmin &&
        mc mb -p local/public-bucket || true &&
        mc anonymous set public local/public-bucket;
        wait $pid
      "

volumes:
  minio_data:
    driver: local